### ISSUE TITLE
[HIGH PRIORITY] Arrumar testes de integração

### ISSUE THREAD

**Issue by danielferragut** [danielferragut/mc921-project1#16]
**Objetivo.**
Atualmente nossos tests de integração não fazem nada, pode passar qualquer coisa que ele da que passa (basicamente o error do lex num da throw la no `t_error`). Também o esquema de pastas num ta muito legal. A gente precisa arrumar os testes de integração e o esquema de pastas, assim como ter um jeito de saber quando o teste dá errado.

**Metas**
Precisamos então:

1. Arrumar as pastas de test. Dentro da pasta `tests`, criar uma pasta `lex` e deixar todos os arquivos de teste lá. Dentro dessa mesma pasta vai ter uma outra pasta ou arquivo relacionado a `data` que são os dados que os testes usam.
2. Bolar um jeito dos testes realmente funcionarem. Um jeito é rodar uma vez, ver se ta certo, guardar a saida num arquivo e comparar o resultado com o do arquivo. Talvez num seja a melhor maneira mas num sei uma melhor.
3. O `t_error` lá do lex só  da print quando tem erro, a gente devia ter um sistema melhor pra isso, ou deve retornar `None` ou jogar uma exception talvez.

**Comment by danielferragut** [comment]
@LuizZucchi Você consegue fazer o 1. pra mim? Essa coisa de import no python me deixa louco, sempre erro e nunca consigo fazer.

**Comment by LuizZucchi** [comment]
1. já está feito e funcionando
2. Eu não entendi muito bem, pelo menos nos testes do lexer eu fiz exatamente isso, arrumei um problema que acontecia em relação às posições dos tokens
3. Eu fiz a exceptions, não dei raise(throw) nela, já que isso para o programa e muda o comportamento dele.

**Comment by LuizZucchi** [comment]
Não sei se entendi seu comentário sobre os testes de integração, mas ideia é que eles não façam nada ainda (só garantir que não tem nada impedindo o modulo de rodar), eles serão aprimorados, a medida que o projeto avançar e eles começarem a ser usados de verdade. Claro tudo isso só vale supondo que eu tenha entendido direito.
