### ISSUE TITLE
[REQ #40 #47] Add init declarator support

### ISSUE THREAD

**Issue by LuizZucchi** [danielferragut/mc921-project1#49]
**Objetivo.**
Add support for `init_declarator` and `init_declarator_list

```
<init_declarator_list> ::= <init_declarator>
                         | <init_declarator_list> , <init_declarator>

<init_declarator> ::= <declarator>
                    | <declarator> = <initializer>

```

**Metas**
- Add `init_declarator` in uc_parser.py
- Add `init_declarator_list` in uc_parser.py
- Add tests in test.uc

**Comment by danielferragut** [comment]
Chamei esse pra luta
